on:
  push:
    branches:
      - master
  



jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'printing folder content'
        run: ls


      - uses: actions/checkout@v3

      - name: 'After printing'
        run: ls
